[project]
name = "smsir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "saeid", email = "samani0019@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["httpx>=0.28", "pydantic>=2.13"]

[build-system]
requires = ["uv_build>=0.11.12,<0.12.0"]
build-backend = "uv_build"
